<?php

namespace ContainerXk6NfMv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KQpcEpWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kQpcEpW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kQpcEpW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'groupe' => ['privates', '.errored..service_locator.kQpcEpW.App\\Entity\\Groupe', NULL, 'Cannot autowire service ".service_locator.kQpcEpW": it references class "App\\Entity\\Groupe" but no such service exists.'],
        ], [
            'groupe' => 'App\\Entity\\Groupe',
        ]);
    }
}
