<?php

namespace ContainerXk6NfMv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_MCMqXbKService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.MCMqXbK' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.MCMqXbK'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'questionid' => ['privates', '.errored..service_locator.MCMqXbK.App\\Entity\\Reponses', NULL, 'Cannot autowire service ".service_locator.MCMqXbK": it references class "App\\Entity\\Reponses" but no such service exists.'],
        ], [
            'questionid' => 'App\\Entity\\Reponses',
        ]);
    }
}
