<?php

namespace ContainerXk6NfMv;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReponsesService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.MCMqXbK.App\Entity\Reponses' shared service.
     *
     * @return \App\Entity\Reponses
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.MCMqXbK": it references class "App\\Entity\\Reponses" but no such service exists.');
    }
}
