<?php

namespace ContainerGip4ZIE;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HPDEQkzService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hPDEQkz' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hPDEQkz'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'concertRepo' => ['privates', 'App\\Repository\\ConcertRepository', 'getConcertRepositoryService', true],
            'groupeRepo' => ['privates', 'App\\Repository\\GroupeRepository', 'getGroupeRepositoryService', true],
        ], [
            'concertRepo' => 'App\\Repository\\ConcertRepository',
            'groupeRepo' => 'App\\Repository\\GroupeRepository',
        ]);
    }
}
