<?php

namespace ContainerOzBP9ng;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DvozGsBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.dvozGsB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.dvozGsB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'concert' => ['privates', 'App\\Repository\\ConcertRepository', 'getConcertRepositoryService', true],
            'groupe' => ['privates', 'App\\Repository\\GroupeRepository', 'getGroupeRepositoryService', true],
        ], [
            'concert' => 'App\\Repository\\ConcertRepository',
            'groupe' => 'App\\Repository\\GroupeRepository',
        ]);
    }
}
