<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAHp8VWu\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAHp8VWu/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAHp8VWu.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAHp8VWu\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerAHp8VWu\App_KernelDevDebugContainer([
    'container.build_hash' => 'AHp8VWu',
    'container.build_id' => '004c2bea',
    'container.build_time' => 1610718169,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAHp8VWu');
