<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPRWtR8q\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPRWtR8q/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPRWtR8q.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPRWtR8q\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerPRWtR8q\App_KernelDevDebugContainer([
    'container.build_hash' => 'PRWtR8q',
    'container.build_id' => '602a8e2f',
    'container.build_time' => 1616525980,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPRWtR8q');
