<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGip4ZIE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGip4ZIE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGip4ZIE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGip4ZIE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGip4ZIE\App_KernelDevDebugContainer([
    'container.build_hash' => 'Gip4ZIE',
    'container.build_id' => '3068a8b6',
    'container.build_time' => 1614243564,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGip4ZIE');
