<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
<<<<<<< HEAD
    'concert_index' => [[], ['_controller' => 'App\\Controller\\ConcertController::index'], [], [['text', '/concert/']], [], []],
    'concert_new' => [[], ['_controller' => 'App\\Controller\\ConcertController::new'], [], [['text', '/concert/new']], [], []],
    'concert_show' => [['id'], ['_controller' => 'App\\Controller\\ConcertController::show'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/concert']], [], []],
    'concert_edit' => [['id'], ['_controller' => 'App\\Controller\\ConcertController::edit'], [], [['text', '/edit'], ['variable', '/', '[^/]++', 'id', true], ['text', '/concert']], [], []],
    'concert_delete' => [['id'], ['_controller' => 'App\\Controller\\ConcertController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/concert']], [], []],
=======
    'app_register' => [[], ['_controller' => 'App\\Controller\\RegistrationController::register'], [], [['text', '/register']], [], []],
    'app_verify_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::verifyUserEmail'], [], [['text', '/verify/email']], [], []],
    'app_confirmation_email' => [[], ['_controller' => 'App\\Controller\\RegistrationController::confirmation'], [], [['text', '/register/confirmation']], [], []],
    'app_login' => [[], ['_controller' => 'App\\Controller\\SecurityController::login'], [], [['text', '/login']], [], []],
    'app_logout' => [[], ['_controller' => 'App\\Controller\\SecurityController::logout'], [], [['text', '/logout']], [], []],
>>>>>>> b01e1af37e1adb74ea6aa1198c055958489f6826
    'live_events_accueil' => [[], ['_controller' => 'App\\Controller\\AccueilController::index'], [], [['text', '/']], [], []],
    'live_events_accueil_admin' => [[], ['_controller' => 'App\\Controller\\AccueilController::adminIndex'], [], [['text', '/admin/']], [], []],
    'live_events_accueil_admin_new_concert' => [[], ['_controller' => 'App\\Controller\\AccueilController::newConcert'], [], [['text', '/admin/add/concert/']], [], []],
    'live_events_accueil_admin_edit_concert' => [['id'], ['_controller' => 'App\\Controller\\AccueilController::editConcert'], ['id' => '\\d+'], [['text', '/edit/concert/'], ['variable', '/', '\\d+', 'id', true], ['text', '/admin']], [], []],
    'live_events_accueil_admin_delete_concert' => [[], ['_controller' => 'App\\Controller\\AccueilController::delete'], [], [['text', '/admin/delete/concert/']], [], []],
    'live_events_Boutique' => [[], ['_controller' => 'App\\Controller\\BoutiqueController::index'], [], [['text', '/boutique']], [], []],
];
