<?php

namespace ContainerTcxfcIV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_FtZMkZZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.FtZMkZZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.FtZMkZZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'message' => ['privates', '.errored..service_locator.FtZMkZZ.App\\Entity\\MessageUrgent', NULL, 'Cannot autowire service ".service_locator.FtZMkZZ": it references class "App\\Entity\\MessageUrgent" but no such service exists.'],
        ], [
            'message' => 'App\\Entity\\MessageUrgent',
        ]);
    }
}
