<?php

namespace ContainerTcxfcIV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getGroupeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.kQpcEpW.App\Entity\Groupe' shared service.
     *
     * @return \App\Entity\Groupe
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.kQpcEpW": it references class "App\\Entity\\Groupe" but no such service exists.');
    }
}
