<?php

namespace ContainerTcxfcIV;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMessageUrgentService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.FtZMkZZ.App\Entity\MessageUrgent' shared service.
     *
     * @return \App\Entity\MessageUrgent
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.FtZMkZZ": it references class "App\\Entity\\MessageUrgent" but no such service exists.');
    }
}
